name = "JuliaPkgTemplatesCommandLineInterface"
uuid = "b8670afd-c0a1-4d96-acf7-d645be7ab2db"
version = "0.0.1"
authors = ["ultimatile <ultimatile@users.noreply.github.com>"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Aqua = "0.8"
ArgParse = "1.2.0"
Mustache = "1.0.21"
PkgTemplates = "0.7.57"
TOML = "1.0.3"
julia = "1.12"

[apps]
jtc = {}

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
