name = "JuliaPkgTemplatesCommandLineInterface"
uuid = "b8670afd-c0a1-4d96-acf7-d645be7ab2db"
authors = ["ultimatile <ultimatile@users.noreply.github.com>"]
version = "0.0.1"

[compat]
julia = "1.10.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
